// Mapping slug -> video YouTube (tutoriel)
// Sources : Alan Thrall, Jeff Nippard, Athlean-X, Calisthenicmovement
const videos: Record<string, string> = {
  "developpe_couche_barre": "https://www.youtube.com/embed/vcBig73ojpE",
  "developpe_couche_halteres": "https://www.youtube.com/embed/VmB1G1K7v94",
  "developpe_couche_a_la_machine": "https://www.youtube.com/embed/cN8iSJ4UWys",
  "ecarte_a_la_poulie": "https://www.youtube.com/embed/taI4X2Lc1iE",
  "ecarte_halteres": "https://www.youtube.com/embed/Z57CtFmRM1E",
  "pompes": "https://www.youtube.com/embed/IODxDxX7oi4",
  "dips_pectoraux": "https://www.youtube.com/embed/2z8g1YVHh2g",
  "developpe_incline_barre": "https://www.youtube.com/embed/8iP2nH0Tnq8",
  "developpe_incline_halteres": "https://www.youtube.com/embed/8iP2nH0Tnq8",
  "ecarte_incline_halteres": "https://www.youtube.com/embed/0Y48onBkz14",
  "pompes_pieds_surélevés": "https://www.youtube.com/embed/IODxDxX7oi4",
  "developpe_militaire_barre": "https://www.youtube.com/embed/2yjwXTZQDDI",
  "developpe_militaire_halteres": "https://www.youtube.com/embed/2yjwXTZQDDI",
  "elevations_frontales": "https://www.youtube.com/embed/hRaoAxMM0Fs",
  "pompes_en_pique": "https://www.youtube.com/embed/7C8b4HUh3Kw",
  "elevations_laterales_halteres": "https://www.youtube.com/embed/3VcKaXpzqRo",
  "elevations_laterales_a_la_poulie": "https://www.youtube.com/embed/3VcKaXpzqRo",
  "oiseau_halteres": "https://www.youtube.com/embed/-t7fuZ0hDJw",
  "face_pull": "https://www.youtube.com/embed/rep-qVOkqQo",
  "oiseau_a_la_machine": "https://www.youtube.com/embed/-t7fuZ0hDJw",
  "tractions": "https://www.youtube.com/embed/eGo4IYlbE5g",
  "tirage_vertical_a_la_poulie": "https://www.youtube.com/embed/CAwf7n6Luuc",
  "tractions_assistees_machine": "https://www.youtube.com/embed/eGo4IYlbE5g",
  "rowing_barre": "https://www.youtube.com/embed/9efZPW3N1X8",
  "rowing_haltere": "https://www.youtube.com/embed/pYcpY20QaE8",
  "tirage_horizontal_a_la_poulie": "https://www.youtube.com/embed/UCXxvVItLoM",
  "rowing_tbar": "https://www.youtube.com/embed/j3Igk5nyZE4",
  "shrugs_barre": "https://www.youtube.com/embed/c0eV7kRq2DQ",
  "shrugs_halteres": "https://www.youtube.com/embed/c0eV7kRq2DQ",
  "souleve_de_terre": "https://www.youtube.com/embed/1ZXobu7JvvE",
  "souleve_de_terre_roumain": "https://www.youtube.com/embed/J2jI1L7Wq8I",
  "souleve_de_terre_roumain_halteres": "https://www.youtube.com/embed/J2jI1L7Wq8I",
  "hip_thrust": "https://www.youtube.com/embed/2SZaPlZem5E",
  "pont_fessier": "https://www.youtube.com/embed/wU8Ki2Y3tR4",
  "leg_curl_allonge": "https://www.youtube.com/embed/ELocC7R9CzY",
  "leg_curl_assis": "https://www.youtube.com/embed/ELocC7R9CzY",
  "nordic_curl": "https://www.youtube.com/embed/eNlN5maN9Dk",
  "squat_barre": "https://www.youtube.com/embed/bEvRGNhYlyE",
  "squat_avant": "https://www.youtube.com/embed/m4yzaCon0eI",
  "presse_a_cuisses": "https://www.youtube.com/embed/CHPHn-FkfE0",
  "hack_squat": "https://www.youtube.com/embed/0tn5K7llV5w",
  "squat_gobelet": "https://www.youtube.com/embed/wUeTqPpWebY",
  "fentes_halteres": "https://www.youtube.com/embed/D7KaRcUTQeE",
  "fentes_bulgares": "https://www.youtube.com/embed/2C-uNgKwCHA",
  "squat_au_poids_du_corps": "https://www.youtube.com/embed/bEvRGNhYlyE",
  "leg_extension": "https://www.youtube.com/embed/YyvSfVjQeL0",
  "curl_barre": "https://www.youtube.com/embed/kwG2ipFRgfo",
  "curl_halteres": "https://www.youtube.com/embed/kwG2ipFRgfo",
  "curl_marteau": "https://www.youtube.com/embed/zC3nLlEvin4",
  "curl_a_la_poulie": "https://www.youtube.com/embed/kwG2ipFRgfo",
  "tractions_supination": "https://www.youtube.com/embed/eGo4IYlbE5g",
  "extension_a_la_poulie": "https://www.youtube.com/embed/kiuw0q0l5Gs",
  "barre_au_front": "https://www.youtube.com/embed/gF9CxIVRuCw",
  "extension_nuque_haltere": "https://www.youtube.com/embed/kiuw0q0l5Gs",
  "dips_sur_banc": "https://www.youtube.com/embed/2z8g1YVHh2g",
  "pompes_serrees": "https://www.youtube.com/embed/IODxDxX7oi4",
  "mollets_debout_machine": "https://www.youtube.com/embed/-M4-G8p8GcQ",
  "mollets_assis": "https://www.youtube.com/embed/JbyjNymH9Ro",
  "mollets_halteres": "https://www.youtube.com/embed/-M4-G8p8GcQ",
  "mollets_au_poids_du_corps": "https://www.youtube.com/embed/-M4-G8p8GcQ",
  "crunch_a_la_poulie": "https://www.youtube.com/embed/Xyd_fa5zoEU",
  "releve_de_jambes_suspendu": "https://www.youtube.com/embed/hDmhKAEQrik",
  "crunch": "https://www.youtube.com/embed/Xyd_fa5zoEU",
  "gainage": "https://www.youtube.com/embed/pSHjTRCQxIw",
};

export function getVideoUrl(slug: string): string | null {
  return videos[slug] || null;
}

export default videos;
